spring.application.name=task-manager

spring.datasource.url=jdbc:mysql://reseau.proxy.rlwy.net:17013/railway
spring.datasource.username=root
spring.datasource.password=abqEznNqHpjbmcpitEqFSdLKzFMzvvhQ

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true